In [1]:
import numpy as np

In [2]:
data = np.genfromtxt("sss.csv", delimiter=',', skip_header=True)
print data

[[  1.  20.  20.   0.   0.   0.   0.   0.]
 [  2.  30.  40.   0.   0.   0.   0.   0.]
 [  3.  50.  30.   0.   0.   0.   0.   0.]
 [  4.  37.  52.   7.   0.   0.   0.   0.]
 [  5.  49.  49.  30.   0.   0.   0.   0.]
 [  6.  20.  26.   9.   0.   0.   0.   0.]
 [  7.  40.  30.  21.   0.   0.   0.   0.]
 [  8.  21.  47.  15.   0.   0.   0.   0.]
 [  9.  17.  63.  19.   0.   0.   0.   0.]
 [ 10.  31.  62.  23.   0.   0.   0.   0.]
 [ 11.  52.  33.  11.   0.   0.   0.   0.]
 [ 12.  51.  21.   5.   0.   0.   0.   0.]
 [ 13.  31.  32.  29.   0.   0.   0.   0.]
 [ 14.  12.  42.  21.   0.   0.   0.   0.]
 [ 15.  52.  41.  15.   0.   0.   0.   0.]
 [ 16.  27.  23.   3.   0.   0.   0.   0.]
 [ 17.  13.  13.   9.   0.   0.   0.   0.]
 [ 18.  57.  58.  28.   0.   0.   0.   0.]
 [ 19.  62.  42.   8.   0.   0.   0.   0.]
 [ 20.  42.  57.   8.   0.   0.   0.   0.]
 [ 21.  27.  68.   7.   0.   0.   0.   0.]
 [ 22.  30.  48.  15.   0.   0.   0.   0.]
 [ 23.  43.  67.  14.   0.   0.   0.   0.]
 [ 24.  58.

In [3]:
location = data[:, :3]
q_matrix = data[:, 3]
et_matrix = data[:, 4]
lt_matrix = data[:, 5]
eet_matrix = data[:, 6]
llt_matrix = data[:, 7]
d_matrix = [[0 for i in range(len(data))] for i in range(len(data))]

In [5]:
import math
for i in range((len(data))):
    for j in range(len(data)):
        dist = math.sqrt(pow(location[i][1]-location[j][1], 2)+pow(location[i][2]-location[j][2], 2))
        d_matrix[i][j] = dist
print d_matrix

[[0.0, 22.360679774997898, 31.622776601683793, 36.235341863986875, 41.012193308819754, 6.0, 22.360679774997898, 27.018512172212592, 43.104524124504614, 43.41658669218482, 34.539832078341085, 31.016124838541646, 16.278820596099706, 23.40939982143925, 38.27531841800928, 7.615773105863909, 9.899494936611665, 53.03772242470448, 47.41307836451879, 43.04648650006177, 48.507731342539614, 29.732137494637012, 52.32590180780452, 47.20169488482379, 38.63935817272331, 31.622776601683793, 27.85677655436824, 12.165525060596439, 29.154759474226502, 39.319206502675, 10.44030650891055, 10.04987562112089, 11.180339887498949, 21.470910553583888, 22.47220505424423, 35.35533905932738, 29.120439557122072, 13.341664064126334, 37.21558813185679, 13.0, 16.492422502470642, 51.86520991955976, 39.81205847478876, 30.4138126514911, 54.405882034941776], [22.360679774997898, 0.0, 22.360679774997898, 13.892443989449804, 21.02379604162864, 17.204650534085253, 14.142135623730951, 11.40175425099138, 26.419689627245813, 2